name: cypress-run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    name: Run Cypress tests (headless)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Verifica que Cypress está correctamente instalado en el runner
      - name: Verify Cypress
        run: npx cypress verify

      # Ejecuta los tests en modo headless con Electron
      - name: Run Cypress
        run: npx cypress run --browser electron --spec "cypress/e2e/**/*.{cy,spec}.{js,ts}"

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
          if-no-files-found: ignore

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**
          if-no-files-found: ignore