name: cypress-run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    name: Run Cypress tests (headless)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Debug list repo files
        run: |
          echo "PWD:" && pwd
          echo ""
          echo "Git tracked files (first 200):"
          git ls-files | sed -n '1,200p'
          echo ""
          echo "JS specs found:"
          find . -type f -name "*.cy.js" -print

      - name: Run Cypress tests
        run: npx cypress run --browser electron --spec "cypress/**/*.cy.{js,ts}"

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
          if-no-files-found: ignore

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**
          if-no-files-found: ignore